import requests
import lxml
from bs4 import BeautifulSoup
import smtplib

my_email = "ericwnelson84@gmail.com"
# passowrd below is a separate password generated by gmail when you add an app password
password = 'vctleaaylxiopnbh'

# below is the url from the product you want history on
url = "https://www.amazon.com/ASUS-Graphics-DisplayPortTM-Full-Coverage-Radiator/dp/B0C8X3RD63/ref=sr_1_1?crid=38FMAI3YIX9PC&keywords=nvidia+4090&qid=1693360511&sprefix=nvidia+4090%2Caps%2C134&sr=8-1&ufe=app_do%3Aamzn1.fos.ac578592-0362-4e0a-958c-0f2dd61d30d4"
header = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8"
}

response = requests.get(url, headers=header)

soup = BeautifulSoup(response.content, "lxml")
# print(soup.prettify())

price = soup.find(class_="a-offscreen").get_text()
price_without_currency = price.split("$")[1].replace(',', '')
price_as_float = float(price_without_currency)
print(price_as_float)

title = soup.find(id="productTitle").get_text().strip()
print(title)
#
BUY_PRICE = 2500

if price_as_float < BUY_PRICE:
    message = f"{title} is now {price}"

    with smtplib.SMTP("smtp.gmail.com", port=587) as connection:
        connection.starttls()
        result = connection.login(my_email, password)
        connection.sendmail(
            from_addr=my_email,
            to_addrs=my_email,
            msg=f"Subject:Amazon Price Alert!\n\n{message}\n{url}".encode("utf-8")
        )

